{% set name = "zernike" %}
{% set version = "0.0.32" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/zernike-{{ version }}.tar.gz
  sha256: 00120a8552301b1d82161d9e86ef7c08cb275bea09798437c5be7728f5d28073

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
    - numpy
    - h5py
  run:
    - python >=3.6
    - numpy
    - h5py

test:
  imports:
    - zernike
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jacopoantonello/zernike
  summary: Python code for Zernike polynomials
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tlambert03
